apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 945253721395.dkr.ecr.us-east-1.amazonaws.com/employee-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
        env:
        - name: __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS
          value: "app.fkvr.xyz,.fkvr.xyz"