apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
  JWT_SECRET: changeme_jwt_secret
  SECRET_WORD: changeme_secret_word
  DATABASE_URL: postgres://postgres:postgres@my-database.cijak4w6yvin.us-east-1.rds.amazonaws.com:5432/postgres



